### ISSUE TITLE
Sane default configuration

### ISSUE THREAD

**Issue by jvtrudel** [coopsymbiotic/coopsymbiotic-ansible#2]
I would like to use your playbook/roles to provision "standalone" (no monitoring or backup) wordpress + civicrm instances.

Your work is really interesting, but it does not have a sane default configuration. Many configuration files and variable are missing. 

I'll work it out and (hopefully) give you my solution as PR. But if you have hints that could save me time, I would appreciate.

**Comment by mlutfy** [comment]
Could you give examples of missing configurations/variables? We only have a handful of private files, such as ssh pubkeys or yubikey config. Although we could indeed add checks to skip monitoring/backups if the variables are empty/unset.

Most of the WordPress/CiviCRM parts in our hosting are handled by Aegir (+ provision_symbiotic), not by our Ansible scripts (although I am slowly moving things around, but it will still rely on Aegir which will provide inventory, because we provide a fair amount of white-label hosting for other companies).

I recommend Jon's Ansible repos: https://github.com/MegaphoneJon?tab=repositories&q=ansible - I think it handles things such as the webserver config, mysql setup, etc, which Aegir handles for us (and Aegir does not really support WordPress, so we duct tape around it).

CiviCRM sysadmins also have a channel on the [CiviCRM chat](https://chat.civicrm.org/civicrm/channels/sysadmin) (Mattermost chat, a self-hosted Slack FOSS clone). I know a few others have Ansible repos, but I can't seem to find them at the moment.

**Comment by jvtrudel** [comment]
Yes I've seen than you rely on Aegir for wordpres/civicrm. Actually, its a bit overkill for our need and and we prefer to focus on the setup of single vm. But I agree that Aegir is a great solution and we will probably head there one day or another. Thank's a lot for the references.

An example of missing configuration is the template `etc/apt/preferences.d/php-symbiotic` in the role php.

I'll play with workpress + civicrm and I'll come back on this issue as soon as possible (but possibly in 2 or 3 weeks).

**Comment by jvtrudel** [comment]
Finally, I do not have time to work on this topic for the moment. 
I close it.
Thank you!
